### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by Unforgiven-wanda**

### CODE REVIEW

**Comment by arelaxend** [comment]
My first try gives an error. It has failed on iOS "Possible unhandled promise rejection".

**Comment by arelaxend** [comment]
There is an error in the last commit. Must replace "icon: () =>" to "icon: (props) =>" in ColorView.js

**Comment by Unforgiven-wanda** [comment]
@arelaxend Strange, I hadn't noticed that. Must come from the fact that I tested it only on Android.
Thanks for pointing it out.

**Comment by arelaxend** [comment]
👍  Good job btw.

**Comment by arelaxend** [comment]
What is going on with the project ? Is it still going on ?

**Comment by Unforgiven-wanda** [comment]
There haven't been updates since more than a month. I wouldn't want this repo to wither and die as it is the best starter boilerplate out there for RN.

**Comment by FruitieX** [comment]
Thanks for the pull request. We have been very busy lately, but I will attempt to take the ball on maintaining this project in about 2 weeks from now. I agree that this is still a useful RN starter kit, and hopefully we can make it even better soon. :)

**Comment by FruitieX** [comment]
The react-native upgrade breaks testing with Enzyme. Reason for this is that react-native depends on React 16 from v0.43 and up, which [Enzyme does not yet support](https://github.com/airbnb/enzyme/issues/928) as React 16 is still in alpha. Might have to wait until Enzyme gains support for React 16.

In the mean-time, I'm maintaining a branch over at [upgrade-dependencies](https://github.com/futurice/pepperoni-app-kit/tree/maintenance/upgrade-dependencies) with the latest versions of packages (and thus broken Enzyme tests). It contains the changes from this PR, so let's continue the discussion over at #209

**Pull request closed without merging**
