### PR TITLE
Added some standard flavors to the Android build

### PR DESCRIPTION
**Pull request by anidel**
Some basic Android flavors. Properties for each flavor can be set up into a property file.
For now only versionName is supported

### CODE REVIEW

**Comment by fabriziomoscon** [comment]
I have not done a lot of work with Android, but reading from here: https://developer.android.com/studio/build/build-variants.html
I choose `buildTypes` rather than flavors so I can specify a sourceSets for each build type where I can have different resources i.e.: API_KEYS and ENV
Also it gives me the possibility to install both debug and production on the same device.

I am still learning which way is better, but so far this works for me. I am interested in hearing your thoughts.

```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
       // ...
    }
    signingConfigs {
        release {
            storeFile file(MYAPP_RELEASE_STORE_FILE)
            storePassword MYAPP_RELEASE_STORE_PASSWORD
            keyAlias MYAPP_RELEASE_KEY_ALIAS
            keyPassword MYAPP_RELEASE_KEY_PASSWORD
        }
    }

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        debug {
            minifyEnabled false
            debuggable true
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
            debuggable false
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}
```

**Comment by anidel** [comment]
Thanks for your comments!
As far as I understood, buildTypes describe the way your development lifecycle (i.e. release, debug) while developing and testing your app whilst productFlavors describe your product 'deployment' characteristics.

For example in Kick we had two build types: Release and Debug and three product flavors: development, staging, release
The first two were mainly used to enable/disable the debug features of the app (logs and an addititional Activity we used during the debug phase to trigger events manually) and the flavors to customise the final APK to deal with a particular backend environment.

Thus, I don't think they should be seen as alternatives to each other, but rather that one compliments the other.

Ideally we should be able to easily configure all of them.

**Comment by fabriziomoscon** [comment]
very good explanation.
I will be curious to see it applied to these files:
https://github.com/futurice/pepperoni-app-kit/tree/master/android/app/src/main/res/values

And yes we should provide an example where to configure all of them!

**Comment by anidel** [comment]
Yeah that'd be a good example indeed!
Will look into it asap.

**Comment by lgvalle** [comment]
This explanation is absolutely correct: https://github.com/futurice/pepperoni-app-kit/pull/75#issuecomment-234000048

* buildTypes: how do you build your apk (obfuscated, debuggable, etc..)
* buildFlavor: what do you put inside your build (environments, country specifics, etc..)

With flavors you can customise sourceSets as well, similar as with buildTypes @fabriziomoscon .
Flavors are also a much powerfult cusmotisation tool, as you can have multi-dimension flavors. For example: 
* freeStaging
* freeRelese
* paidStaging
* paidRelese
(...)

More info here: http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants

**Pull request closed without merging**
