### PR TITLE
Upgrade react-native to v0.26.2 and react to v15.0.2

### PR DESCRIPTION
**Pull request by fabriziomoscon**
- cannot update react further since v15.1.0 has a bug that impact react-native
- import propTypes from react
- remove unused react-dom
- upgrade dev-dependencies react test libraries

tested on real Android device.
Maybe someone can help me test on iPhone or simulator since I don't have a mac available right now...

### CODE REVIEW

**Comment by jevakallio** [comment]
Thanks for the contribution! @tino-junge @krivachy are you able to test this?

IIRC react-dom is, or at least was, needed for the Enzyme unit tests, so let's make sure to rimraf node_modules, npm install from scratch and make sure they still work too.

**Comment by jevakallio** [comment]
Change diff looks good.

**Comment by fabriziomoscon** [comment]
I installed all from scratch. Tested on real Android device. I have working all day yesterday with this. Cannot test on iPhone.
If `react-dom` is necessary for testing we can add it back to `devDependencies` not `production` dependencies. But All tests pass. Might be worth adding the project to travis so PR are tested automatically. 
I can do that into another PR if you are keen.
I have also wanted to improve a guide on how to extend this with navigation and more screens, but I am going to develop a bit more before doing that.

Thanks for creating this I really enjoying using it

**Comment by jevakallio** [comment]
@fabriziomoscon thanks for the clarification. We'll get this tested and merged!

Regarding running tests on Travis, we are looking into whether we could use our Bitrise CI for that, as it would allow us to test the native iOS build steps as well. In any case we'll put some CI in place next week, this week we're a little short on time.

**Comment by krivachy** [comment]
@fabriziomoscon Thanks for your contribution! The tests don't pass, because of react-dom missing, can you please add react-dom dependency back? Should be fine in the devDependencies as you mentioned. And yes, we would ideally like bitrise, but if we can't get that working then travis will do.

```
> Kindling@1.0.0 test /Users/akri/dev/pepperoni-app-kit
> mocha src/**/*.spec.js

react-dom is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation
/Users/akri/dev/pepperoni-app-kit/node_modules/enzyme/build/react-compat.js:106
      throw e;
      ^

Error: Cannot find module 'react-dom'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /Users/akri/dev/pepperoni-app-kit/node_modules/enzyme/build/react-compat.js:103:18
    at Object.<anonymous> (/Users/akri/dev/pepperoni-app-kit/node_modules/enzyme/build/react-compat.js:180:5)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/akri/dev/pepperoni-app-kit/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:357:32)
```

Also the iOS version doesn't seem to be starting up. I didn't have time to debug it, but will look into it sometime on the weekend.

**Comment by fabriziomoscon** [comment]
this is done for you @krivachy 
If an external library needs a particular module to run they should include the module on that library.
But for today that will fix it.

I can't help with the iOS test though

**Comment by fabriziomoscon** [comment]
I think to make iOS compiling I will need some upgrade script which I am figuring out...
if anybody has done that before any advise is welcome

**Comment by jevakallio** [comment]
I think something like this would be helpful:  https://twitter.com/matzatorski/status/737557627656249346

No need to take immediate action. I can test this tomorrow when I'm back from holidays.

**Comment by jevakallio** [comment]
@fabriziomoscon tested on iOS, works fine! Only issue is that I'm getting a NPM `unmet peer dependency` warning for `react 15.0.2` not matching `react-dom` and `react-addons-test-utils` versions.

If you update these `package.json` lines, this PR should be good to go:

```
    "react-addons-test-utils": "15.0.2",
    "react-dom": "15.0.2",
```

**Comment by fabriziomoscon** [comment]
@jevakallio 
I managed to compile and run the app on ios simulator. My steps:

```
cd ios
pod --version // 1.0.0
pod repo update
pod install
rnpm upgrade
react-native run-ios
```

as a side effect this had also changed few files: https://github.com/futurice/pepperoni-app-kit/pull/29/commits/344c6e454e28ceb357dc26e270102c620d7b601a

I am not 100% sure about these changes but after I run them all works for me

**Comment by jevakallio** [comment]
@fabriziomoscon I cherry picked the version upgrade commit https://github.com/futurice/pepperoni-app-kit/pull/29/commits/887172c80dd534127adb5b40a29faebe57ca2f3f and merged it with https://github.com/futurice/pepperoni-app-kit/pull/36, followed by the pod repo update with https://github.com/futurice/pepperoni-app-kit/pull/37.

I could not take the `rnpm upgrade` commit, because it overrode intentional changes we have made to the project files. I will handle any necessary updates manually as needed, but for now the 0.26 version works on Android and iOS without any further changes.

Thanks for contributing this! I will now close the PR as the relevant commits are already in master.

**Pull request closed without merging**
