### PR TITLE
Get rid of ImmutableJS

### PR DESCRIPTION
**Pull request by FruitieX**
"Immutable is god awful" - Justin

Relevant Flowdock thread:

immutable

### CODE REVIEW

**Comment by FruitieX** [comment]
Maybe a better solution would be to use [seamless-immutable](https://github.com/rtfeldman/seamless-immutable)

**Comment by loiclouvet** [comment]
A suggestion would be to not call `toJS()` on ViewContainer(s) and use [react-immutable-proptypes](https://github.com/HurricaneJames/react-immutable-proptypes), then you can pass immutable objects (records as well) to View(s) as props.

**Comment by Unforgiven-wanda** [comment]
Another possible solution would be switching to [seamless-immutable](https://github.com/futurice/pepperoni-app-ki), something like the best of both worlds.

**Comment by FruitieX** [comment]
Yep, seamless-immutable should be a better option than getting rid of immutable data structures entirely. I'll also investigate making this a user choice when they setup their project.

**Pull request closed without merging**
